### ISSUE TITLE
Add CI job to test new released packages.

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/ci#46] opened 2018-07-03 15:33 UTC
To ensure the Packages work as expected we should craete a CI job and run it every time a new package version is released.

**Comment by jodh-intel** [comment] 2018-07-04 06:44
Duplicate of #10.

**Comment by GabyCT** [comment] 2021-05-26 16:53
Closing this issue as we do not have packages in kata 2.x

**Closed by GabyCT** 2021-05-26 16:53 UTC
