### ISSUE TITLE
arm: investigate docker test failures

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#205] opened 2019-07-19 19:10 UTC
I see that the ARM CI jobs have been failing since yesterday morning. 

Most common failures are:
```
16:53:53 Stderr: Error response from daemon: Cannot pause container 4600e32d206fe51fb77f38ca6086464be19a3f05dae92e0d8f30caf24e143e6d: cannot pause a stopped container: unknown
```

and

```
11:59:37 Stderr: Error response from daemon: Container 19d372a9608651bb23036bae66de68a3c6bfb6678768d018f638525193c349c3 is not running
```

any idea @Pennyzct ?

Thanks.

**Comment by Pennyzct** [comment] 2019-07-22 06:11
Hi @chavafg 
Sorry for the trouble. I have seen this error repeatedly this morning. I will firstly try to reproduce it on my local machine, and then try to figure out where it went wrong. ;)

**Comment by chavafg** [comment] 2019-07-22 14:21
no problem, thanks @Pennyzct 😃

**Comment by Pennyzct** [comment] 2019-07-23 03:49
Hi~ @chavafg I may have detected the cause. It has been this PR [#osbuilder/332](https://github.com/kata-containers/osbuilder/pull/332), upgrading fedora from 28 to 30 in docker image when building the rootfs.
If we patched this PR, busybox image will crash. I have collected some related log, but I haven't found out the reason why only busybox image crashed. 😢😭
```
Jul 23 11:15:48  kata-proxy[33284]: time="2019-07-23T11:15:48.416884388+08:00" level=info msg="systemd-coredump[81]: Failed to send coredump datagram: Broken pipe\n" name=kata-proxy pid=33284 sandbox=3c7bccc707d8512f5ae2a99ae85d5d7208c52d1d50754a03ca7f086cf050eccc source=agent
Jul 23 11:15:48 kata-proxy[33284]: time="2019-07-23T11:15:48.419322078+08:00" level=info msg="time=\"2019-07-23T03:15:48.122604785Z\" level=debug msg=\"process exited\" debug_console=false name=kata-agent pid=76 sandbox=3c7bccc707d8512f5ae2a99ae85d5d7208c52d1d50754a03ca7f086cf050eccc source=agent status=139\n" name=kata-proxy pid=33284 sandbox=3c7bccc707d8512f5ae2a99ae85d5d7208c52d1d50754a03ca7f086cf050eccc source=agent
```
It looked to me that `systemd-coredump` had something wrong with writing coredump, `Broken pipe error`. Have you guys ever encountered similar error? 😵 @chavafg @grahamwhaley @jcvenegas 
I will keep digging up and will fire a PR to make aarch64 using fedora 28 back, to make the CI act normal in the first place.

**Comment by chavafg** [comment] 2019-07-24 14:52
Thanks @Pennyzct, arm CI is already passing 😄
do you want to keep this issue open until you find the issue when using Fedora 30? or should we close this one and reopen https://github.com/kata-containers/osbuilder/issues/334?

**Comment by jcvenegas** [comment] 2019-07-29 17:51
Fixed in osbuilder closing issue.

**Closed by jcvenegas** 2019-07-29 17:51 UTC
Labels: bug, needs-review
